@API_HostAddress = http://localhost:5056

GET {{API_HostAddress}}/customersales/
Accept: application/json

GET {{API_HostAddress}}/customersales/dumpjson
Accept: application/json

GET {{API_HostAddress}}/weatherforecast/
Accept: application/json

###
